//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.42.
// 
namespace LAC.ContextInformation.MocaWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MocaWSPortBinding", Namespace="http://server.mocaWS.personalities.moca/")]
    public partial class MocaWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public MocaWebService() {
            this.Url = "http://139.82.24.238:3636/mocaWS/mocaWS";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:isConnected", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isConnected() {
            object[] results = this.Invoke("isConnected", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginisConnected(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("isConnected", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndisConnected(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:askCIS", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public deviceContextWS askCIS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("askCIS", new object[] {
                        arg0});
            return ((deviceContextWS)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaskCIS(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("askCIS", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public deviceContextWS EndaskCIS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((deviceContextWS)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:requestCIS", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public deviceContextWS requestCIS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg2) {
            object[] results = this.Invoke("requestCIS", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((deviceContextWS)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginrequestCIS(string arg0, string arg1, long arg2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("requestCIS", new object[] {
                        arg0,
                        arg1,
                        arg2}, callback, asyncState);
        }
        
        /// <remarks/>
        public deviceContextWS EndrequestCIS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((deviceContextWS)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:requestTicketCIS", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ticketWS requestTicketCIS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("requestTicketCIS", new object[] {
                        arg0,
                        arg1});
            return ((ticketWS)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginrequestTicketCIS(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("requestTicketCIS", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public ticketWS EndrequestTicketCIS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ticketWS)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getTicketCISInfo", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public deviceContextWS[] getTicketCISInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ticketWS arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool arg1) {
            object[] results = this.Invoke("getTicketCISInfo", new object[] {
                        arg0,
                        arg1});
            return ((deviceContextWS[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTicketCISInfo(ticketWS arg0, bool arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTicketCISInfo", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public deviceContextWS[] EndgetTicketCISInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((deviceContextWS[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:askLISAreas", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] askLISAreas() {
            object[] results = this.Invoke("askLISAreas", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaskLISAreas(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("askLISAreas", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndaskLISAreas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:askLISAreaOfDevice", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string askLISAreaOfDevice([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("askLISAreaOfDevice", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaskLISAreaOfDevice(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("askLISAreaOfDevice", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndaskLISAreaOfDevice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:askLISDevices", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] askLISDevices() {
            object[] results = this.Invoke("askLISDevices", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaskLISDevices(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("askLISDevices", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndaskLISDevices(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:askLISDevicesOfArea", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] askLISDevicesOfArea([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("askLISDevicesOfArea", new object[] {
                        arg0});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaskLISDevicesOfArea(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("askLISDevicesOfArea", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndaskLISDevicesOfArea(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:requestDeviceEventLIS", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public deviceRegionWS[] requestDeviceEventLIS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg2) {
            object[] results = this.Invoke("requestDeviceEventLIS", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((deviceRegionWS[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginrequestDeviceEventLIS(string arg0, long arg1, int arg2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("requestDeviceEventLIS", new object[] {
                        arg0,
                        arg1,
                        arg2}, callback, asyncState);
        }
        
        /// <remarks/>
        public deviceRegionWS[] EndrequestDeviceEventLIS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((deviceRegionWS[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:requestDeviceEventTicketLIS", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ticketWS requestDeviceEventTicketLIS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("requestDeviceEventTicketLIS", new object[] {
                        arg0});
            return ((ticketWS)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginrequestDeviceEventTicketLIS(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("requestDeviceEventTicketLIS", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public ticketWS EndrequestDeviceEventTicketLIS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ticketWS)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:requestAreaEventLIS", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public deviceRegionWS[] requestAreaEventLIS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg2) {
            object[] results = this.Invoke("requestAreaEventLIS", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((deviceRegionWS[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginrequestAreaEventLIS(string arg0, long arg1, int arg2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("requestAreaEventLIS", new object[] {
                        arg0,
                        arg1,
                        arg2}, callback, asyncState);
        }
        
        /// <remarks/>
        public deviceRegionWS[] EndrequestAreaEventLIS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((deviceRegionWS[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:requestAreaEventTicketLIS", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ticketWS requestAreaEventTicketLIS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("requestAreaEventTicketLIS", new object[] {
                        arg0});
            return ((ticketWS)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginrequestAreaEventTicketLIS(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("requestAreaEventTicketLIS", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public ticketWS EndrequestAreaEventTicketLIS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ticketWS)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getEventTicketLISInfo", RequestNamespace="http://server.mocaWS.personalities.moca/", ResponseNamespace="http://server.mocaWS.personalities.moca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public deviceRegionWS[] getEventTicketLISInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ticketWS arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool arg1) {
            object[] results = this.Invoke("getEventTicketLISInfo", new object[] {
                        arg0,
                        arg1});
            return ((deviceRegionWS[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetEventTicketLISInfo(ticketWS arg0, bool arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getEventTicketLISInfo", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public deviceRegionWS[] EndgetEventTicketLISInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((deviceRegionWS[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.mocaWS.personalities.moca/")]
    public partial class deviceContextWS {
        
        private int advertisementPeriodicityField;
        
        private bool apChangeField;
        
        private int cpuUsageField;
        
        private string currentAPMacAddressField;
        
        private long deltaTField;
        
        private int energyLevelField;
        
        private long freeMemoryField;
        
        private bool ipChangeField;
        
        private string mobileHostIPAddressField;
        
        private string mobileHostMacAddressField;
        
        private string networkMaskField;
        
        private bool onLineField;
        
        private long timeStampField;
        
        private int wlanConnectivityLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int advertisementPeriodicity {
            get {
                return this.advertisementPeriodicityField;
            }
            set {
                this.advertisementPeriodicityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool apChange {
            get {
                return this.apChangeField;
            }
            set {
                this.apChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cpuUsage {
            get {
                return this.cpuUsageField;
            }
            set {
                this.cpuUsageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currentAPMacAddress {
            get {
                return this.currentAPMacAddressField;
            }
            set {
                this.currentAPMacAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long deltaT {
            get {
                return this.deltaTField;
            }
            set {
                this.deltaTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int energyLevel {
            get {
                return this.energyLevelField;
            }
            set {
                this.energyLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long freeMemory {
            get {
                return this.freeMemoryField;
            }
            set {
                this.freeMemoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ipChange {
            get {
                return this.ipChangeField;
            }
            set {
                this.ipChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mobileHostIPAddress {
            get {
                return this.mobileHostIPAddressField;
            }
            set {
                this.mobileHostIPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mobileHostMacAddress {
            get {
                return this.mobileHostMacAddressField;
            }
            set {
                this.mobileHostMacAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string networkMask {
            get {
                return this.networkMaskField;
            }
            set {
                this.networkMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool onLine {
            get {
                return this.onLineField;
            }
            set {
                this.onLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int wlanConnectivityLevel {
            get {
                return this.wlanConnectivityLevelField;
            }
            set {
                this.wlanConnectivityLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.mocaWS.personalities.moca/")]
    public partial class deviceRegionWS {
        
        private string areaField;
        
        private string macAddressField;
        
        private sbyte typeEventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string macAddress {
            get {
                return this.macAddressField;
            }
            set {
                this.macAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sbyte typeEvent {
            get {
                return this.typeEventField;
            }
            set {
                this.typeEventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.mocaWS.personalities.moca/")]
    public partial class ticketWS {
        
        private int idField;
        
        private double timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
}
